services:
  db:
    image: postgres:17           
    container_name: db_api_apollo     
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: password  
      POSTGRES_DB: apollo_api_development   
    ports:
      - "5432:5432"